name: Docker Image CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true  # Ensure submodules are checked out

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/4get:latest

    - name: Dockerhub login
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Docker push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/4get:latest
